name: CI - Run Spring Boot Tests

# Run this job on pull requests targeting develop or main branches
on:
  pull_request:
    branches:
      - develop
      - main

# Define the jobs to be executed
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17 (or any version your project requires)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      # Step 3: Cache Maven dependencies to speed up the workflow
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Install dependencies and run tests using Maven
      - name: Run Unit Tests
        run: mvn clean test
